language: elixir
elixir:
  - 1.5.3
  - 1.6.4
otp_release:
  - 19.3.6
  - 20.3.2
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
